/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobrauliocalix;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Braulio
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agg_Arista = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Norigen = new javax.swing.JTextField();
        Apeso = new javax.swing.JTextField();
        Ndestino = new javax.swing.JTextField();
        Agregar_Arista = new javax.swing.JButton();
        Prueba_ruta = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        AgArista = new javax.swing.JButton();
        PruebaRuta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Instrucciones = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("Nodo Origen");

        jLabel4.setText("Nodo Destino");

        jLabel5.setText("Tamaño/peso");

        Agregar_Arista.setText("Agregar Arista");
        Agregar_Arista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agregar_AristaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Agg_AristaLayout = new javax.swing.GroupLayout(Agg_Arista.getContentPane());
        Agg_Arista.getContentPane().setLayout(Agg_AristaLayout);
        Agg_AristaLayout.setHorizontalGroup(
            Agg_AristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agg_AristaLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(Agg_AristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(Agg_AristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Norigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ndestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apeso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
            .addGroup(Agg_AristaLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(Agregar_Arista)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Agg_AristaLayout.setVerticalGroup(
            Agg_AristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agg_AristaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(Agg_AristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Norigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(Agg_AristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Ndestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(Agg_AristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Apeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Agregar_Arista)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel6.setText("Nodo origen");

        jLabel7.setText("Nodo Final");

        jButton1.setText("Comprobar Ruta");

        javax.swing.GroupLayout Prueba_rutaLayout = new javax.swing.GroupLayout(Prueba_ruta.getContentPane());
        Prueba_ruta.getContentPane().setLayout(Prueba_rutaLayout);
        Prueba_rutaLayout.setHorizontalGroup(
            Prueba_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Prueba_rutaLayout.createSequentialGroup()
                .addGroup(Prueba_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Prueba_rutaLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(Prueba_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Prueba_rutaLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Prueba_rutaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(104, 104, 104)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Prueba_rutaLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButton1)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        Prueba_rutaLayout.setVerticalGroup(
            Prueba_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Prueba_rutaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(Prueba_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(Prueba_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 370));

        AgArista.setText("Agregar Arista");
        AgArista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgAristaMouseClicked(evt);
            }
        });
        getContentPane().add(AgArista, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, -1, -1));

        PruebaRuta.setText("Probar Ruta");
        PruebaRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PruebaRutaMouseClicked(evt);
            }
        });
        getContentPane().add(PruebaRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 480, -1, -1));

        Instrucciones.setEditable(false);
        Instrucciones.setColumns(20);
        Instrucciones.setRows(5);
        Instrucciones.setText("Para agregar nodos, solo hay que hacer click \nsobre el panel de la izquierda, para agregar \naristas, usar los botones para probar una ruta \nentre nodos, usar el boton e ingresar los datos.\nespero sea de su agrado inge ");
        jScrollPane1.setViewportView(Instrucciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 430, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Webp.net-resizeimage.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 250, 200));

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/562290-naruto-asi-son-aldeas-ocultas.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1200, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgAristaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgAristaMouseClicked
        if (Cnodos >= 2) {
            Agg_Arista.pack();
            Agg_Arista.setModal(true);
            Agg_Arista.setLocationRelativeTo(this);
            Agg_Arista.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "se necesitan al menos dos nodos creados para generar aristas \ngracias");
        }

    }//GEN-LAST:event_AgAristaMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        Cnodos++;
        System.out.println("posicion de x : " + evt.getX());
        System.out.println("posicion de y: " + evt.getY());
        System.out.println("Cantidad de nodos: "+Cnodos);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void Agregar_AristaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_AristaMouseClicked
        int N1 = 0, N2 = 0, peso = 0;
        try {
            N1 = Integer.parseInt(Norigen.getText());
            N2 = Integer.parseInt(Ndestino.getText());
            peso = Integer.parseInt(Apeso.getText());

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "tiene que ingresar numeros");
        }
        if (N1 < 0 || N1 > 15 || N2 < 0 || N2 > 15 || peso < 0 || N1 == N2) {
            JOptionPane.showMessageDialog(this, "ha ingresado mal un valor solo se permite un maximo de 15 nodos");
        } else {
            System.out.println("simon si vale");
        }
    }//GEN-LAST:event_Agregar_AristaMouseClicked

    private void PruebaRutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PruebaRutaMouseClicked
        // TODO add your handling code here:
        if (Cnodos >= 2) {
            Prueba_ruta.pack();
            Prueba_ruta.setModal(true);
            Prueba_ruta.setLocationRelativeTo(this);
            Prueba_ruta.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "se necesitan al menos dos nodos creados para probar una ruta \ngracias");
        }

    }//GEN-LAST:event_PruebaRutaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgArista;
    private javax.swing.JDialog Agg_Arista;
    private javax.swing.JButton Agregar_Arista;
    private javax.swing.JTextField Apeso;
    private javax.swing.JTextArea Instrucciones;
    private javax.swing.JTextField Ndestino;
    private javax.swing.JTextField Norigen;
    private javax.swing.JButton PruebaRuta;
    private javax.swing.JDialog Prueba_ruta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
/*
    SOLICITAR INTERFAZ GRAFICA PARA V TRUE
    SOLICITAR INTERFAZ GRAFICA PARA E TRUE
    REPRESENTAR EN UNA ESTRUCTURA DE DATO TRUE(ARRAYLIST)
    DIBUJAR EL GRAFO G FALSE
    CALCULAR EL GRADO DEL GRAFO FALSE
    CALCULAR LA SUMA DED LOS GRADOS DE LOS VERTICES V FALSE
    CALCULAR EL GRADO MENOR ENTRE LOS VERTICES FALSE
     */
    ArrayList grafo = new ArrayList();
    int[][] Madyacencia = new int[15][15];// se pone un maximo de 15 por pura conveniencia
    int Cnodos = 0; //cantidad de nodos
}
